# wrangler.toml

[env.production]
name = "cf-workers-sub"
compatibility_date = "2025-01-26"

[env.production.vars]
TOKEN = "your-admin-token-here"        # 管理员令牌
LINK = """
https://example1.com/subscription
https://example2.com/subscription
vmess://eyJ2IjoiMiIsInBzIjoi...
"""                                    # 默认订阅链接

[[env.production.kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"
